-- CURSORES
-- PRONCIPALES HERRAMINTAS 
/*
	* ULILES PARA GESTIONAR GRANDES CANTIDADES DE DATOS
	* ESTA FORMADO POR UN CONJUNTO DE REGISTRO DEVUELTOS POR UNA INSTRUCCION 
	  SQL DE TIPO SELECT
	* SON SEGMENTOS DE MEMORIA UTILIZADOS PARA REALIZAR OPERACIONES CON LAS 
	  FILAS DE DATOS RECUPERADOS.
*/
DECLARE
CURSOR
BEGIN
  

EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;

