
-- CURSORES EXPLICITOS
-- PRONCIPALES HERRAMINTAS 
/*
	* ULILES PARA GESTIONAR GRANDES CANTIDADES DE DATOS
	* ESTA FORMADO POR UN CONJUNTO DE REGISTRO DEVUELTOS POR UNA INSTRUCCION 
	  SQL DE TIPO SELECT
	* SON SEGMENTOS DE MEMORIA UTILIZADOS PARA REALIZAR OPERACIONES CON LAS 
	  FILAS DE DATOS RECUPERADOS.
*/
-- TIPOS DE CURSORES
	--CURSORES IMPLICITOS
/*
	* DEBEN DEVOLVER UNA SOLA FILA, SINO DELVOLVERA ERROR.
EJEMPLO DE CURSOR IMPLICITO
*/
DECLARE
	-- %TYPE = COPIA EL FORMATO QUE TIENE EL CAMPO EN LA BASE DE DATOS 
	lsalario  empleados.salario%TYPE
	lcedula  empleados.cedula%TYPE
BEGIN
	SELECT salario, cedula
	INTO lsalario, lcedula
	FROM empleados
	WHERE nombre = 'Juan'
	AND apellidos = 'Rojas Comas';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;

